-- DOCTORES
INSERT INTO DOCTORES (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ESPECIALIDAD) VALUES ('JUAN'    , 'SÁNCHEZ'  , 'LÓPEZ'   , 'CARDIÓLOGIA'     );
INSERT INTO DOCTORES (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ESPECIALIDAD) VALUES ('ROCIO'   , 'ORTIZ'    , 'LUNA'    , 'PEDIATRÍA'       );
INSERT INTO DOCTORES (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ESPECIALIDAD) VALUES ('JESSICA' , 'MORALES'  , 'RUIZ'    , 'NEUROLOGÍA'      );
INSERT INTO DOCTORES (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ESPECIALIDAD) VALUES ('LUISA'   , 'CHÁVEZ'   , 'MARTÍNEZ', 'DERMATOLOGÍA'    );
INSERT INTO DOCTORES (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, ESPECIALIDAD) VALUES ('KIMBERLY', 'RODRÍGUEZ', 'SÁNCHEZ' , 'MEDICINA INTERNA');
-- CONSULTORIOS
INSERT INTO CONSULTORIOS (NUMERO_CONSULTORIO, PISO) VALUES (501,5);
INSERT INTO CONSULTORIOS (NUMERO_CONSULTORIO, PISO) VALUES (205,2);
INSERT INTO CONSULTORIOS (NUMERO_CONSULTORIO, PISO) VALUES (302,3);
INSERT INTO CONSULTORIOS (NUMERO_CONSULTORIO, PISO) VALUES (101,1);
INSERT INTO CONSULTORIOS (NUMERO_CONSULTORIO, PISO) VALUES (410,4);
-- CITAS
INSERT INTO CITAS (ID_DOCTOR, ID_CONSULTORIO, HORARIO_CONSULTA, NOMBRE_PACIENTE) VALUES (5, 1, TIMESTAMP '2025-05-09 14:00:00', 'ROSARIO SÁNCHEZ PÉREZ');
INSERT INTO CITAS (ID_DOCTOR, ID_CONSULTORIO, HORARIO_CONSULTA, NOMBRE_PACIENTE) VALUES (5, 2, TIMESTAMP '2025-05-09 15:00:00', 'LUIS MANUEL RIOS LUNA');
INSERT INTO CITAS (ID_DOCTOR, ID_CONSULTORIO, HORARIO_CONSULTA, NOMBRE_PACIENTE) VALUES (5, 3, TIMESTAMP '2025-05-09 16:00:00', 'MARGARITA SÁNCHEZ');
INSERT INTO CITAS (ID_DOCTOR, ID_CONSULTORIO, HORARIO_CONSULTA, NOMBRE_PACIENTE) VALUES (5, 4, TIMESTAMP '2025-05-09 17:00:00', 'MARIA LÓPEZ LÓPEZ');
INSERT INTO CITAS (ID_DOCTOR, ID_CONSULTORIO, HORARIO_CONSULTA, NOMBRE_PACIENTE) VALUES (5, 5, TIMESTAMP '2025-05-09 18:00:00', 'ALBERTO MEJÍA TORRES');