DROP TABLE IF EXISTS CITAS;
DROP TABLE IF EXISTS DOCTORES;
DROP TABLE IF EXISTS CONSULTORIOS;

CREATE TABLE DOCTORES (
 ID_DOCTOR        INTEGER      NOT NULL AUTO_INCREMENT,
 NOMBRE           VARCHAR(45)  NOT NULL,
 APELLIDO_PATERNO VARCHAR(45)  NOT NULL,
 APELLIDO_MATERNO VARCHAR(45)  NOT NULL,
 ESPECIALIDAD     VARCHAR(100) NOT NULL,
 PRIMARY KEY (ID_DOCTOR)
);

CREATE TABLE CONSULTORIOS (
 ID_CONSULTORIO     INTEGER NOT NULL AUTO_INCREMENT,
 NUMERO_CONSULTORIO INTEGER NOT NULL,
 PISO               INTEGER NOT NULL,
 PRIMARY KEY (ID_CONSULTORIO)
);

CREATE TABLE CITAS (
 ID_CITA          INTEGER   NOT NULL AUTO_INCREMENT,
 ID_DOCTOR        INTEGER   NOT NULL,
 ID_CONSULTORIO   INTEGER   NOT NULL,
 HORARIO_CONSULTA TIMESTAMP NOT NULL,
 NOMBRE_PACIENTE  VARCHAR(135),
 PRIMARY KEY (ID_CITA),
 FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTORES(ID_DOCTOR) ON DELETE CASCADE,
 FOREIGN KEY (ID_CONSULTORIO) REFERENCES CONSULTORIOS(ID_CONSULTORIO) ON DELETE CASCADE
);